# Generated by Django 5.1.6 on 2025-08-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brssheet',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
