# Generated by Django 5.1.6 on 2025-08-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_brssheet_deskripsi'),
    ]

    operations = [
        migrations.AddField(
            model_name='brssheet',
            name='nama_tabel',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
