# Generated by Django 5.1.6 on 2025-08-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_brssheet_nama_tabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brssheet',
            name='nama_tabel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
