# Generated by Django 5.1.6 on 2025-09-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_alter_brssheet_nama_tabel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brssheet',
            old_name='nama_tabel',
            new_name='nama_tabel_lengkap',
        ),
    ]
