# Generated by Django 5.1.6 on 2025-09-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_rename_nama_tabel_brssheet_nama_tabel_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='brssheet',
            name='nama_tabel_ver2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
