# Generated by Django 5.1.6 on 2025-11-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_brssheet_nama_tabel_ver2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brssheet',
            name='nama_tabel_lengkap',
        ),
    ]
