# Generated by Django 5.1.6 on 2025-11-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0007_remove_brssheet_nama_tabel_lengkap'),
    ]

    operations = [
        migrations.AddField(
            model_name='brsexcel',
            name='deskripsi_abstrak',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brsexcel',
            name='jumlah_halaman',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brsexcel',
            name='ukuran_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
