# Generated by Django 5.1.6 on 2025-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_brsexcel_deskripsi_abstrak_brsexcel_jumlah_halaman_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brssheet',
            name='deskripsi',
        ),
    ]
