"""
Django settings for statsync project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-exm4+fxv!(8v319@qhm3)(=yfg-$j&h2j5+vr-ovulu!63i#ir'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['.vercel.app', 'localhost', '127.0.0.1', '10.35.1.105']
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'statsync-capstone.up.railway.app']

CSRF_TRUSTED_ORIGINS = ['https://statsync-capstone.up.railway.app']
# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',  # Add this line
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    
    'apps.myadmin',
    'apps.myuser',
    'apps.myauth',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware', 
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this line
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'statsync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'statsync.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     # 'default': {
#     #     'ENGINE': 'django.db.backends.sqlite3',
#     #     'NAME': BASE_DIR / 'db.sqlite3',
#     # }
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'statsync' ,
#         #'USER': 'userku', # user kirribili
#         #'PASSWORD': '12345',
#         'PASSWORD': '220304',
#         #'HOST': '192.168.3.187',  # ip wifi kirribili
#         #'USER': 'userbaru',
#         'USER': 'root',
#         #'HOST': '10.35.1.83',  # ip wifi bps jatim
#         'HOST': 'localhost',
#         'PORT': '3306',      # or the port on which your MySQL server is listening
#     }
# }

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'railway' ,
        #'USER': 'userku', # user kirribili
        #'PASSWORD': '12345',
        'PASSWORD': 'dzCcTAWrvVzvQcsvgskHiRrMwAUEjYWN',
        #'HOST': '192.168.3.187',  # ip wifi kirribili
        #'USER': 'userbaru',
        'USER': 'root',
        #'HOST': '10.35.1.83',  # ip wifi bps jatim
        'HOST': 'caboose.proxy.rlwy.net',
        'PORT': '38031',      # or the port on which your MySQL server is listening
    }
}

AUTH_USER_MODEL = 'myauth.CustomUser'  # Ganti dengan nama app kamu

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
    # os.path.join(BASE_DIR, 'staticfiles'),

]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Folder untuk mengumpulkan static files saat deploy
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
